export class PdfInfo {

    doorHeight:string =""
    doorWidth :string =""
    ProductHeight:string =""
    ProductWidth:string =""
    oldDoorHeight:string=""
    oldDoorWidth:string=""
    oldProductHeight:string=""
    oldProductWidth:string=""
    EmployeeSign1:string =""
    EmployeeSign2:string =""
    EmployeeSign3:string =""
    EmployeeSign4:string =""
    EmployeeSign5:string =""
    CustomerSign1:string =""
    CustomerSign2:string =""
    CustomerSign5:string =""
    CustomerSign3:string =""
    CustomerSign4:string =""
    Date :string =""
    EmployeePrint1 :string =""
    EmployeePrint2 :string =""
    EmployeePrint3 :string =""
    EmployeePrint4 :string =""
    EmployeePrint5 :string =""
    CustomerPrint1:string =""
    CustomerPrint2:string =""
    CustomerPrint3:string =""
    CustomerPrint4:string =""
    CustomerPrint5:string =""
    PrintName:string =""
}
